### PR TITLE
Word wrap

### PR DESCRIPTION
**Pull request by vanceza**
Add word wrap

### CODE REVIEW

**Comment by WuTheFWasThat** [comment]
display flex works nicely, and I didn't know of its existence.  thanks for fixing that also

**Comment by vanceza** [comment]
Eugh, that's because the space before the line wraps around doesn't get rendered, because we're using browser word-wrap...

**Comment by WuTheFWasThat** [comment]
I think maybe we just need `white-space: pre;`?

**Comment by WuTheFWasThat** [comment]
it doesn't work perfectly when spaces are at the end of the line (especially easy to see with multiple spaces) but it's good enough for now

**Comment by WuTheFWasThat** [comment]
https://github.com/WuTheFWasThat/vimflowy/commit/d330de138ca6afe0aa6712eeb3d7940fa537e5c2

**Comment by vanceza** [comment]
Thanks Jeff

**Pull request closed without merging**
