### PR TITLE
Use latest version of node-sass

### PR DESCRIPTION
**Pull request by vanceza**
Seems to work fine locally

### CODE REVIEW

**Comment by WuTheFWasThat** [comment]
but I don't want to assume what version of node people are on.  this is why i restricted to node-sass 1.2.3 (and it worked for me):  https://github.com/sahat/hackathon-starter/issues/222

i'm curious what issue you run into

**Comment by vanceza** [comment]
I'm on the latest version of node, and I run into the opposite problem (where node-sass 1.2.3 doesn't work on the newer node version). More info when I'm at a computer.

**Comment by vanceza** [comment]
Node v0.12.4
This is the issue I ran into: https://github.com/sass/node-sass/issues/653. There does not appear to be a version of node-sass which supports both node v0.10 and v0.12.

**Comment by WuTheFWasThat** [comment]
wow.  I'll just update node

**Comment by WuTheFWasThat** [comment]
i verified the opposite problem.  very stupid situation with node-sass and node

**Pull request merged**
