### PR TITLE
Aliasing

### PR DESCRIPTION
**Pull request by vanceza**
This contains:
- Data structure changes explained here: https://github.com/WuTheFWasThat/vimflowy/pull/55
- Support for 'yc' command

Not yet supported:
- 'Collapsed' is still a per-id property
- You cannot add cloned siblings or cycles (by which I mean, there is no UI guard against this but it will explode if you do)

Things that are expected to work include marks; navigation; edit type actions; removing, adding, and moving rows; and undo/redo.

### CODE REVIEW

**Comment by vanceza** [comment]
Resolves https://github.com/WuTheFWasThat/vimflowy/issues/18

**Comment by vanceza** [comment]
Redid everything so it's up-to-date with master and rebased.

**Comment by WuTheFWasThat** [comment]
you should make movement work properly

if i have
- blah
- blah
- bullet
- clone of bullet
- blah

j and k don't move properly, you need the cursor.coffee updates along the lines of what i'd made in jeff_aliasing, i think

**Comment by vanceza** [comment]
"You cannot add cloned siblings or cycles (by which I mean, there is no UI guard against this but it will explode if you do)"

Do you still have the problem for non-sibling clones?

Agree it should be fixed either way.

**Comment by WuTheFWasThat** [comment]
ah yeah - seems to work better with non-siblings :+1: 

i noticed a slightly odd bug where if you use `k` and it goes from a row to its parent, the cursor disappears

**Comment by vanceza** [comment]
I've been trying to track down that #@*( bug for weeks off and on, I'm well aware

**Comment by WuTheFWasThat** [comment]
unfortunately, rendering is out of scope for my tests :/ i can try to help figure it out tonight or the weekend though

**Comment by WuTheFWasThat** [comment]
2 bugs i found:   
1. cloning anything that is marked removes the mark
2. when clones of each other are on the screen, the cursor is always on one when on the other

BTW, the clone tests are in a different folder than everything else

**Comment by vanceza** [comment]
I'd prefer to list any non-blocking bugs under the main bug tracker rather than this PR so I can distinguish from now on. I know of some more issues with marks I'll put there now.

**Comment by vanceza** [comment]
This can be safely closed now, correct?

**Comment by WuTheFWasThat** [comment]
yea

**Pull request closed without merging**
