### PR TITLE
Makefile

### PR DESCRIPTION
**Pull request by vanceza**
-Add a makefile
-compile_static.sh actually starts the server (not compatible with already running nodemon currently)
-Support for sourcing compile_static.sh

### CODE REVIEW

**Comment by WuTheFWasThat** [comment]
thanks - this is great.  I left some minor comments

**Comment by WuTheFWasThat** [comment]
looks good now!  let me spend a bit of time seeing if we can get rid of the bashism.  I'm not an expert on different shells though...

**Comment by WuTheFWasThat** [comment]
jeez, this whole strategy of starting a server and then curling it is kinda miserable.  it *should* be much easier... but I can't figure out how to get the binary node_modules/.bin/connect-assets to work - it chokes on compiling sass mixins, and also doesn't concatenate (after i removed use of the mixins).  options I see...
1. dig into connect-assets source code, figure out how to do it properly
2. use something besides connect-assets

**Comment by WuTheFWasThat** [comment]
I attempted to do it from connect-assets source code... for posterity:

```
connect_assets = require('connect-assets')
Assets = require('./node_modules/connect-assets/lib/assets')

# if process.argv.length < 2

outDir = process.argv[2]

options = {
  buildDir: outDir
  compile: true
  paths: ['assets/js', 'assets/css']
}
assets = new Assets connect_assets._parseOptions options

assets.compile (err) ->
  if err
      console.log 'ERROR:', err
      console.log err.stack
      process.exit 1
  console.log 'success!'
  process.exit 0
```

it kinda works, except again it's not cool with sass mixins... so I think waht you have is fine.  gonna accept the pull request and maybe we can figure out a better solution one day

**Comment by WuTheFWasThat** [comment]
I have merged it manually:  https://github.com/WuTheFWasThat/vimflowy/commit/aa0095cc41a9671d6f6521858ac10a9f52abeac1

**Comment by vanceza** [comment]
I think starting the server and wgetting it is a good approach and I've seen it used before. It's pretty foolproof.
I would switch from 'curl localhost:8080/index.html' and a copy to 'wget -r localhost:8080/index.html' if anything.

**Pull request closed without merging**
