### PR TITLE
Change stylesheet

### PR DESCRIPTION
**Pull request by vanceza**
Usage is from the javascript console:

`changeStylesheet("app")` is the default stylesheet
`changeStylesheet("inverted")` could for example be a color-inverted stylesheet, once we write one.

I didn't add any UI to switch stylesheets yet, just the internal functionality.

### CODE REVIEW

**Comment by vanceza** [comment]
See also bug #12

**Comment by vanceza** [comment]
I can't get a connect-assets to work in prod currently. It's because of this bug: https://github.com/adunkman/connect-assets/issues/311.

I can
1. Get that fixed upstream in connect-assets, and we can turn fingerprinting off, which solves everything. In the meantime, probably work around the problem by stripping out fingerprints during the copy in the build phase.
2. As you suggest, we can drop connect-assets in favor or something else (another asset-serving system or plain CSS would be the obvious suggestions)
3. I can switch the build script to use recursive wget instead of copying the 'public' folder, which works around this problem and gives us a lot of independence, BUT which means that we need every included resource to be discoverable (which looks a tiny bit ugly for JS-loaded stylesheets)

What do you want to go with?

**Comment by WuTheFWasThat** [comment]
I'd say 2 is fine - we don't have to use connect-assets.  it's probably pointless (concatenating the assets, that is) in this case, and will make our lives easier.  anything that can deal with sass and coffee should be fine

do you have an opinion?

**Comment by WuTheFWasThat** [comment]
I think I know how to maybe do it with connect-assets.  you can do stuff like
!= css("app", { id: 'mainStylesheet' })

and we can also split it out into stylable stuff vs. everything else, perhaps.  I can experiment with it another day (I'm going to bed now)

**Comment by vanceza** [comment]
I can't do `!= css("app", { id: 'mainStylesheet' })` from javascript so that doesn't help.

**Comment by vanceza** [comment]
Given that we want a static site at the end anyway, why not drop both 'connect' and 'connect-assets' in favor of a build system? I favor `make` together with a monitor system like `nodemon` or `incron`. `grunt` is also popular in node circles.

**Comment by WuTheFWasThat** [comment]
re first comment:  my idea is not to do that part in javascript.  i would explain further but, re second comment: i'm totally fine with dropping connect-assets.  I've seen gulp used a lot for the actual build part, I know slightly more about it than grunt but don't have a strong preferences.

**Comment by vanceza** [comment]
To not do it in javascript, we'd need to drop support for adding additional stylesheets after build time, I think? Which is fine.

**Comment by WuTheFWasThat** [comment]
what do you think of this:  https://github.com/WuTheFWasThat/vimflowy/pull/40

**Comment by vanceza** [comment]
Closing in favor of #40.

**Pull request closed without merging**
